### ISSUE TITLE
Relative references are not supported

### ISSUE THREAD

**Issue by zandaleph** [bali182/autocomplete-json#64]
I'm trying to write a SchemaProvider which provides a collection of related schemata which share some underlying types.  Rather than copy-pasting the shared types into each schema, I'd prefer to use references to a shared schema which defines the shared types.  For security / deployment reasons I cannot put these on a webserver (ruling out http references), and because I don't know the details of other user's Atom installs I can't use absolute file references either.  Based on https://spacetelescope.github.io/understanding-json-schema/structuring.html#reuse , it seems that relative urls should be viable, however the following example seems to fail:

```
# common.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "id": "my.common.schema.json",
  "definitions": {
    "numberArray": {
      "type": "array",
      "items": {
        "type": "number"
      }
    }
  }
}
```

```
# specific.schema.json

{
  "$schema": "http://json-schema.org/schema#",
  "id": "my.specific.schema.json",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {"type": "number"},
      "digits": {"$ref": "common.schema.json#/definitions/Metrics"},
    },
    "required": ["id", "replicaNo", "taskTypeId"]
  }
}
```

When I supply `file:///path/to/specific.schema.json` to autocomplete-json through the https://github.com/bali182/autocomplete-json/wiki/SchemaProvider interface it does not work.  However, if I pull the common definition into the file, it does.

From reading `json-schema-resolver.js` and `json-schema-loader.js`, it appears you don't use the current uri / id as a base url for resolving relative uris.  Could you take a look at supporting relative references?

**Comment by bali182** [comment]
Hey @zandaleph thanks for bringing this up!

I didn't really flesh out the file resolving method, since the base schemas/schemastore ones didn't need them, but I really want have a proper implementation of this at some point.

Now as far as I know json schemas use URIs for referencing other schemas - or at least that's what I'm using in this package - be that in the local document, a file, a http endpoint or else. Do you know if there is a standard way to express relative file paths using an URI? Also, what do you think the resolution should be relative to? Most logical solution seems to be the schema referencing the the other schema, but it is not guaranteed for a schema to be on the local system - technically it's possible for a `http://...` schema to point to a `file://` schema - so it's hard to make assumptions about what we are making the resolution path relative to.

Let me know what you think!

**Comment by zandaleph** [comment]
If you look at the code for `uri-js`, the uri.reference field can be "same-document", "relative", "absolute", or possibly something else.  I believe the cases I'm concerned about are only the ones where that takes the value of "relative".  I forget what exactly that means in uri terms, but I believe it is defined by the uri spec.

So, according again to https://spacetelescope.github.io/understanding-json-schema/structuring.html#the-id-property , relative urls should be resolved relative to the id as a base url.  However, it is not clear what should be done when the id isn't a fully qualified url (at least not from that tutorial).

For my selfish purposes, i'm supplying a non-url id (or rather, I should be; the dots I'm currently using could be confused for an implicit domain name) in hopes that the path used to load the schema would be used instead or to support filling in what the id field does not.  Then I would be able to use file-relative references like I'm hoping to.  However, I'm not sure what is specified by the JSON-schema spec here - I'm fairly new to this space.

And for further wrenches - there's probably a security concern about a JSON-schema loaded via `http://` that references a `file://` schema, so i'd say naively that should be banned, but that's a bit beyond what I'm asking for at present :)

**Comment by bali182** [comment]
The id concept makes a lot of sense, sorry I didn't get it the first time. The resolution order however is tricky since it has to be done async, and if let's say schema `A` references a child from `B` by id, but the resolution of `A` was requested first (or only) then it has no way of knowing that someone might provide the schema later from which `B` can be resolved. Or am I overcomplicating this? It would trivial if you provide all root URIs (be that remote, file or whatever) for your schemas where any piece of the final schema resides, they are all resolved first, then the final schema is pieced together from the already resolved sub-schemas.

This however as far as I see would be a breaking change, since currently you can only provide a single path to a schema in a provider and the above requires multiple.

Also right now I'm really thinking about figuring out a proper way to do this and create a separate module with good test coverage to tackle this problem and move it entirely out of the scope of the plugin, since I feel like it will get a bit too messy in here...

**Comment by bali182** [comment]
Created a repo at https://github.com/bali182/resolve-json-schema

**Comment by UziTech** [comment]
Going to close this as stale. If it is still an issue we can reopen it.
