### ISSUE TITLE
Worth investigating: Slow activation time

### ISSUE THREAD

**Issue by deiga** [bali182/autocomplete-json#68]
On my atom setup it takes 347ms to activate this package on a window reload and I don't even have any JSON files open.
Could we somehow shave some time from here? Maybe add caching of the schemas? (Not really sure why it takes so long to activate anyway)

**Comment by bali182** [comment]
Thanks for the raising this. Slow activation of this specific package might be due to the transpilation (`"use babel"`) on the fly, schemas are cached as much as possible. 

#66 delays activation until a json file is being opened, didn't realise this was an issue, so I will push out a release with that change as soon as possible!

**Comment by bali182** [comment]
Released v5.5.0 it has the delayed activation.
