### ISSUE TITLE
json schema for json schema

### ISSUE THREAD

**Issue by tj** [bali182/autocomplete-json#70]
this looks awesome! without a fileMatch thing, is it possible to use http://json-schema.org/draft-04/schema? cheers

**Comment by tj** [comment]
actually better question: is possible to trick this project into using a local schema? Just to confirm everything is working properly before I send it to the registry.

Thanks!

**Comment by tj** [comment]
nvm not a big deal, it would be cool to easily preview the schema you're working on but I think I've got it figured out!

**Comment by bali182** [comment]
Hey, that was quick! Previewing / testing a json schema isn't easy currently, you have to create a plugin for that and either link it locally or release it as an atom package.

This is how you do it:
https://github.com/bali182/autocomplete-json/wiki/SchemaProvider

The guide doesn't say how to test it since that belongs to the topic of atom plugin development, but all you have to do is

- be in the folder where your newly created plugin is
- `apm link .`  - atom package manager (`apm`) should come with your atom installation
- `atom --dev` - open atom in dev mode

You can open the console (https://discuss.atom.io/t/how-to-view-console-window-debugger/10098) and observe what's going on if you want.

**Comment by tj** [comment]
Thanks man! One thing that isn't clear, is once I have submitted to schemastore (http://json.schemastore.org/up.json), it seems to not pick up my schema. I tried restarting atom etc but no luck.

**Comment by bali182** [comment]
That's strange, I see you updated the catalog as well. Going to take a look, there might be something with the schema that's not supported.

**Comment by bali182** [comment]
Some underlying HTTP layer was caching the schema catalog extremely agressively, so your new entry didn't show up. It should be fixed in `autocomplete-json@v5.5.2` which should be up now.

**Comment by tj** [comment]
awesome that worked! this is sweet
